---
title: "Feature Selection Genes of Kidney Cancer with mRMRe (TCGA-KIRC)"
output:
# pdf_document: default
  html_document: 
    default
  github_document: 
    df_print: paged
    html_preview: FALSE
    keep_html: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_format = "all") })      
---

  
```{r error=TRUE, message=FALSE, warning=FALSE, include=FALSE, purl=FALSE, results='hide'}
## This chunk automatically generates a text .R version of this script when running within knitr.
input  = knitr::current_input()  # filename of input document
output = paste(tools::file_path_sans_ext(input), 'R', sep = '.')
try(knitr::purl(input,output,documentation=2,quiet=T), silent = TRUE)
# Avoid duplicate label error of knitr::purl
options(knitr.duplicate.label = 'allow')
# Code to browse the markdown file with renderized images.
knitr::opts_chunk$set(
  fig.path = "figs/render-"
)
```


# Installing and Loading Libraries            


```{r message=FALSE, warning=FALSE, paged.print=FALSE}

if(!require('tidyverse')){install.packages('tidyverse')}
if(!require('grid')){install.packages('grid')}
if(!require('gridExtra')) {install.packages('gridExtra')} #  Provides a number of user-level functions to work with "grid" graphics
if(!require('ggrepel')) {install.packages('ggrepel')} 
if(!require('cowplot')) {install.packages('cowplot')} # Provides various features that help with creating publication-quality figures
if(!require('GOplot')) {install.packages('GOplot')}
if(!require('VennDiagram')) {install.packages('VennDiagram')}
if(!require('futile.logger')) {install.packages('futile.logger')} # For VennDiagramLogger

```

# Load Data

```{r}
load(file = "../data/2.gsign_kidney.rda")

gsign_kidney["fs.mRMR", "signature"][[1]] <- list(c("AL353637.1", "AR",  "DPP6", "FOXJ1", "FOXJ1", "GNB3", "HHLA2", "IL4", "LIMCH1", "LINC01732", "OTX1", "SAA1", "SEMA3G", "ZIC2"))
 
gsign_kidney <- gsign_kidney %>%
  dplyr::filter(!id %in% c("sign.3", "sign.4",  "sign.11", "sign.13", "sign.14", "fs.genetic", "fs.mRMR.status", "fs.mRMR.time")) %>%
  mutate(id =  fct_recode(id,
    Ha.2014.CaInfo = "sign.1",
    Zhan.2015.CMMM = "sign.2",
    Dai.2016.Oncotarget = "sign.5",
    Wan.2017.IJCancer = "sign.6",
    Chang.2018.Medicine = "sign.7",
    YuanLeiChen.2018.JCP = "sign.8",
    Hu.2019.IJMS = "sign.9",
    LiangChen.2018.JCP = "sign.10",
    #Pan.2019.MSM.5genes = "sign.11", # removed
    Pan.2019.MSM = "sign.12",
    Wu.2019.FrontiersOnco = "sign.15",
    Jiang.2020.ACS = "sign.16",
    Zou.2020.PeerJ = "sign.17",
    LingChen.2020.Hereditas = "sign.18",
    DCosta.2020.SciReports = "sign.19",
    GBM = "filt.gbm",
    Rpart = "filt.rpart",
    XGBoost = "filt.xgboost",
    Boruta = "fs.boruta",
    RFE = "fs.mlr.rfe",
    mRMR = "fs.mRMR"
    ))

rownames(gsign_kidney) <- gsign_kidney$id

```


# Venn diagrams of signatures

```{r}

genes_DEA_M0 <- readLines("../2_gene_expression_differentiation/genes.DEA.M0.vs.M1.lst")
genes_DEA_NT <- readLines("../2_gene_expression_differentiation/genes.DEA.NT.vs.TP.lst")
# genes_risk <- readLines("../3_gene_mutational_survival/genes_mutated.highrisk.lst")
genes_eqtls <- readLines("../data/genes_kidney_cortex_eqtls.lst")
genes_papers <- unique(unlist(gsign_kidney$signature[c(1:14)])) # readLines("../data/genes_papers.lst")

genes_DEA_M0 <- gsub("-", ".", genes_DEA_M0)
genes_DEA_NT <- gsub("-", ".", genes_DEA_NT)
genes_eqtls <- gsub("-", ".", genes_eqtls)
genes_papers <- gsub("-", ".", genes_papers)
genes_mRMR <- c("AL353637.1", "AR",  "DPP6", "FOXJ1", "GNB3", "HHLA2", "IL4", "LIMCH1", "LINC01732", "OTX1", "SAA1", "SEMA3G", "ZIC2")


genes_selection <-  unique(union(union(union(genes_DEA_M0, genes_DEA_NT), genes_papers), genes_eqtls))
genes_all <- union(union(union(union(genes_DEA_M0, genes_DEA_NT), genes_eqtls), genes_papers), genes_mRMR)

named.list.for.venn <-
   list(`DEA_M0` = genes_DEA_M0,
        `DEA_NT` = genes_DEA_NT,
        genes_eqtls = genes_eqtls,
        genes_papers = genes_papers)

library(VennDiagram)

futile.logger::flog.threshold(futile.logger::ERROR, name = "VennDiagramLogger")
pvenn <- venn.diagram(
    x = named.list.for.venn,
    #filename = "../plots/fig2_venn.png",
    filename = NULL,
    category.names = c("Genes DEA M0 vs M1" , "Genes DEA NT vs TP" , "Genes Kidney eqtls", "Genes of Selected Papers"),
    imagetype = "png",
    #col = "transparent",,
    # Circles
    lwd = 2,
    lty = 'blank',
    fill = c("#999999", "#E69F00", "#56B4E9", "#009E73"), #"#ed85b0"
  #alpha = 0.50,
   # label.col = c("orange", "white", "orange", "white", "darkblue", "white", "darkgreen", "white"),
    cex = .9,
    fontfamily = "sans",
    #fontface = "bold",
    #cat.col = c("darkblue", "darkgreen", "orange"),
    cat.fontfamily = "sans",
    cat.cex = .75,
    #cat.fontface = "bold",
    cat.default.pos = "outer",
    cat.dist = c(0.055, 0.055, 0.1, 0.1)
    )

  #rm(list = setdiff(ls(), c("pvenn", "gsign_kidney")))
 rm(list = setdiff(ls(), c("pvenn", "gsign_kidney", "genes_DEA_M0", "genes_DEA_NT", "genes_eqtls", "genes_papers", "genes_mRMR", "genes_all"))) 
```

<!-- ```{r} -->

<!-- genes_DEA_M0 <- readLines("../2_gene_expression_differentiation/genes.DEA.M0.vs.M1.lst") -->
<!-- genes_DEA_NT <- readLines("../2_gene_expression_differentiation/genes.DEA.NT.vs.TP.lst") -->
<!-- genes_eqtls <- readLines("../data/genes_kidney_cortex_eqtls.lst") -->
<!-- genes_papers <- unique(unlist(gsign_kidney$signature[c(1:14)]))  -->

<!-- genes_DEA_M0 <- gsub("-", ".", genes_DEA_M0) -->
<!-- genes_DEA_NT <- gsub("-", ".", genes_DEA_NT) -->
<!-- genes_eqtls <- gsub("-", ".", genes_eqtls) -->
<!-- genes_papers <- gsub("-", ".", genes_papers) -->

<!-- genes_mRMR <- c("AL353637.1", "AR",  "DPP6", "FOXJ1", "GNB3", "HHLA2", "IL4", "LIMCH1", "LINC01732", "OTX1", "SAA1", "SEMA3G", "ZIC2") -->

<!-- genes_selection <-  unique(union(union(union(genes_DEA_M0, genes_DEA_NT), genes_papers), genes_eqtls)) -->

<!-- genes_all <- union(union(union(union(genes_DEA_M0, genes_DEA_NT), genes_eqtls), genes_papers), genes_mRMR) -->

<!-- named.list.for.venn <- -->
<!--    list(genes_mRMR = genes_mRMR,  -->
<!--         `DEA_NT` = genes_DEA_NT, -->
<!--         genes_eqtls = genes_eqtls, -->
<!--         genes_papers = genes_papers, -->
<!--         `DEA_M0` = genes_DEA_M0) -->

<!-- futile.logger::flog.threshold(futile.logger::ERROR, name = "VennDiagramLogger") -->

<!-- pvenn <- -->
<!--   venn.diagram( -->
<!--     x = named.list.for.venn, -->
<!--     filename = NULL, -->
<!--     category.names = c("Genes mRMR", "DEA NT vs TP" , "Genes Kidney eQTLS", "Genes of Selected Papers", "DEA M0 vs M1" ), -->
<!--     imagetype = "png", -->
<!--     # Circles -->
<!--     lwd = 2, -->
<!--     lty = 'blank', -->
<!--     fill = c("#ed85b0", "#E69F00", "#56B4E9", "#009E73", "#999999"), # -->
<!--     #alpha = 0.50, -->
<!--     #label.col = c("orange", "white", "orange", "white", "darkblue", "white", "darkgreen", "white"), -->
<!--     cex = 1, -->
<!--     fontfamily = "sans", -->
<!--     #fontface = "bold", -->
<!--     #cat.col = c("darkblue", "darkgreen", "orange"), -->
<!--     cat.fontfamily = "sans", -->
<!--     cat.cex = .75, -->
<!--     #cat.fontface = "bold", -->
<!--     cat.default.pos = "outer", -->
<!--     cat.just =  list( c(0.5, 1), c(0, 1), c(0.1, 0.1),  c(0.5, 1), c(1, 0))  -->
<!--     #cat.dist = c(0.1, 0.5, 0.1, 0.1, c(0.001,) -->
<!--     ) -->

<!-- rm(list = setdiff(ls(), c("pvenn", "gsign_kidney", "genes_DEA_M0", "genes_DEA_NT", "genes_eqtls", "genes_papers", "genes_mRMR", "genes_all"))) -->

<!-- ``` -->


# Load data DEA

```{r}

load("../data/1.data.processed.rda")
load("../data/dea.M0.M1.rda")
load("../data/dea.NT.TP.rda")

```


```{r message=FALSE, warning=FALSE, include=FALSE}

mydata <- dea.NT.TP %>% 
  dplyr::filter(dea.NT.TP$symbol %in% genes_all) 

mydata <- mydata %>% 
    mutate(gene_label=ifelse(symbol %in% genes_mRMR, symbol, "")) %>%    # For only genes on mRMR
    mutate(sig=ifelse((logFC >= 3 & pvalue < 0.05), "up", ifelse((logFC <= -3 & pvalue < 0.05), "down", "notsig")))

colours <- setNames(c( "#009392", "darkgrey", "#CF597E"), c("down", "notsig", "up"))
# colours <- setNames(c("cornflowerblue", "grey", "firebrick"), c("down", "notsig", "up"))
# c('#CF597E','#E9E29C','#009392')
p1 <- ggplot(mydata, aes(x = logFC, y = -log10(FDR), col=sig)) +
  geom_point(alpha = 0.5)  +
  scale_color_manual(values=colours) +
  geom_vline(xintercept=c(-3,3), linetype="dotted") +
  geom_hline(yintercept=c(-log10(0.01)), linetype="dotted") +
  ggtitle("Normal vs Tumor") +
  xlab("Gene expression change\n log2(FC)") +
  ylab("Significance\n -log10(FDR)") +
  xlim(c(-50,50)) +
  ylim(c(-2,550)) +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"), legend.position="none") +
  geom_label_repel(data = mydata[mydata$logFC > -3 & mydata$logFC < 3 , ],
           aes(label=gene_label),
           seed = 123,
           xlim = c(NA, 25),  # reduce overlaps
           ylim = c(430, NA),
           direction = "both",
           max.time = 5,
           max.iter = 1e5,
           force = 1,
           size = 3,
           max.overlaps = Inf) +
  geom_label_repel(data = mydata[mydata$logFC > 3, ],
            aes(label=gene_label),
            seed = 123,
            xlim = c(30, NA),  # reduce overlaps
            ylim = c(-1,500),
            direction = "y",
            max.time = 5,
            max.iter = 1e5,
            force = 2,
            size = 3,
            max.overlaps = Inf) +
  geom_label_repel(data = mydata[mydata$logFC < -3, ],
            aes(label=gene_label),
            seed = 123,
            xlim = c(NA, -30),  # reduce overlaps
            ylim = c(0, 450),
            #nudge_x = -30  - subset(mydata, logFC < -3)$logFC,
            hjust = 1,
            direction = "y",
            max.time = 5,
            max.iter = 1e5,
            force = 1,
            size = 3,
            max.overlaps = Inf)


mydata <- dea.M0.M1 %>% 
  dplyr::filter(symbol %in% genes_all) 


mydata <- mydata %>% 
    mutate(gene_label=ifelse(symbol %in% genes_mRMR, symbol, "")) %>%    # For only genes on mRMR
    mutate(sig=ifelse((logFC >= 2 & pvalue < 0.05), "up", ifelse((logFC <= -2 & pvalue < 0.05), "down", "notsig")))

p2 <- ggplot(mydata, aes(x = logFC, y = -log10(FDR), col=sig)) +
  geom_point(alpha = 0.5)  +
  scale_color_manual(values=colours) +
        geom_vline(xintercept=c(-2,2), linetype="dotted") +
        geom_hline(yintercept=c(-log10(0.05)), linetype="dotted") +
        ggtitle("Non-metastatic vs Metastatic") +
        xlab("Gene expression change\n log2(FC)") +
        ylab("Significance\n -log10(FDR)") +
        xlim(-15,15) +
        ylim(-1,70) +
        theme(plot.margin = unit(c(0, 0, 0, 0), "cm"), legend.position="none") +
        geom_label_repel(data = mydata[mydata$logFC < -2, ],
                         aes(label=gene_label),
                         seed = 123,
                         xlim = c(NA, -7.5),  # reduce overlaps
                         ylim = c(0, 60),
                         nudge_x = -7.5  - subset(mydata, logFC < -2)$logFC,
                         hjust = 1,
                         direction = "y",
                         max.time = 5,
                         max.iter = 1e5,
                         force = 0.2,
                         size = 3,
                         max.overlaps = Inf) +
        geom_label_repel(data = mydata[mydata$logFC > 2, ],
                         aes(label=gene_label),
                         seed = 123,
                         xlim = c(7.5, NA),  # reduce overlaps
                         ylim = c(-1, 70),
                         nudge_x = 7.5  - subset(mydata, logFC > 2)$logFC,
                         direction    = "y",
                         hjust = 0,
                         max.time = 5,
                         max.iter = 1e5,
                         force = 1,
                         size = 3,
                         max.overlaps = Inf) +
          geom_label_repel(data = mydata[mydata$logFC > -2 & mydata$logFC < 2 , ],
                         aes(label=gene_label),
                         seed = 123,
                         xlim = c(NA, NA),  # reduce overlaps
                         ylim = c(40, NA),
                         direction = "both",
                         max.time = 5,
                         max.iter = 1e5,
                         force = 20,
                         size = 3,
                         max.overlaps = Inf)


  
    
  pdf("../plots/fig2_venn_volcanos.pdf", width = 15, height = 4)
    cowplot::plot_grid(NULL, grobTree(pvenn), NULL, p1, NULL,  p2, NULL, 
                       label_size = 20,
                       labels = c("", "a", "", "b", "", "c", ""), 
                       nrow=1, rel_widths = c(0.1, 1.1, 0.2, 1, 0.2, 1, 0.1))
  dev.off()

        
```


# Matrix of Intersections

```{r}

cols <- c("gene", "genes_DEA_M0", "genes_DEA_NT", "genes_eqtls", "genes_papers",  as.character(gsign_kidney$id))
genes_matrix <- as.data.frame(matrix(nrow = length(genes_all), ncol = length(cols)))
colnames(genes_matrix) <- cols
genes_matrix$gene <- genes_all
rownames(genes_matrix) <- genes_all
  
for(sign_id in gsign_kidney$id) {
  genes_matrix[,sign_id]  <- as.numeric(genes_matrix$gene %in% gsign_kidney[sign_id, "signature"][[1]])
}

gene_list <- list(genes_DEA_NT, genes_DEA_M0,  genes_eqtls, genes_papers) # genes_risk,
names(gene_list) <- c("genes_DEA_NT", "genes_DEA_M0", "genes_eqtls", "genes_papers") # "genes_risk", 

for(l in names(gene_list)) {
  genes_matrix[, l] <- as.numeric(genes_matrix$gene %in% gene_list[[l]]) 
}

rownames(dea.M0.M1) <- dea.M0.M1$symbol
rownames(dea.NT.TP) <- dea.NT.TP$symbol

genes_matrix$logFC.M0.M1 <-  dea.M0.M1[genes_matrix$gene,"logFC"]
genes_matrix$logFC.NT.TP <-  dea.NT.TP[genes_matrix$gene,"logFC"]

genes_matrix$logFC.M0.M1[is.na(genes_matrix$logFC.M0.M1)] <- 0
genes_matrix$logFC.NT.TP[is.na(genes_matrix$logFC.NT.TP)] <- 0

genes_matrix$nlog10FDR.M0.M1 <- -log10(dea.M0.M1[genes_matrix$gene,"FDR"])
genes_matrix$nlog10FDR.NT.TP <- -log10(dea.NT.TP[genes_matrix$gene,"FDR"])

genes_matrix$nlog10FDR.NT.TP[is.na(genes_matrix$nlog10FDR.NT.TP)] <- 0
genes_matrix$nlog10FDR.M0.M1[is.na(genes_matrix$nlog10FDR.M0.M1)] <- 0

# sets_list <- c("Ha.2014.CaInfo", "Zhan.2015.CMMM", "Dai.2016.Oncotarget", "Wan.2017.IJCancer", "Chang.2018.Medicine", 
#           "YuanLeiChen.2018.JCP", "Hu.2019.IJMS", "LiangChen.2018.JCP", "Pan.2019.MSM", "Wu.2019.FrontiersOnco", "Jiang.2020.ACS", 
#           "Zou.2020.PeerJ", "LingChen.2020.Hereditas", "DCosta.2020.SciReports", "filt.gbm", "Rpart", "XGBoost", "Boruta",
#           "RFE", "mRMR", "genes_DEA_M0", "genes_DEA_NT", "genes_eqtls") 

mRMR <- gsign_kidney["mRMR","signature"][[1]]
Boruta <- gsign_kidney["Boruta","signature"][[1]]
RFE <- gsign_kidney["RFE","signature"][[1]]
GBM <- gsign_kidney["GBM","signature"][[1]]
Rpart <- gsign_kidney["Rpart","signature"][[1]]
XGBoost <- gsign_kidney["XGBoost","signature"][[1]]


Pan.2019.MSM <- gsign_kidney["Pan.2019.MSM","signature"][[1]]
Jiang.2020.ACS <- gsign_kidney["Jiang.2020.ACS","signature"][[1]]
Chang.2018.Medicine  <- gsign_kidney["Chang.2018.Medicine","signature"][[1]]
Zou.2020.PeerJ   <- gsign_kidney["Zou.2020.PeerJ","signature"][[1]]
Wan.2017.IJCancer   <- gsign_kidney["Wan.2017.IJCancer","signature"][[1]]
Zhan.2015.CMMM <- gsign_kidney["Zhan.2015.CMMM","signature"][[1]]
Dai.2016.Oncotarget <- gsign_kidney["Dai.2016.Oncotarget","signature"][[1]]
YuanLeiChen.2018.JCP <- gsign_kidney["YuanLeiChen.2018.JCP","signature"][[1]]
Hu.2019.IJMS <- gsign_kidney["Hu.2019.IJMS","signature"][[1]]
LiangChen.2018.JCP <- gsign_kidney["LiangChen.2018.JCP","signature"][[1]]
Wu.2019.FrontiersOnco <- gsign_kidney["Wu.2019.FrontiersOnco","signature"][[1]]
LingChen.2020.Hereditas <- gsign_kidney["LingChen.2020.Hereditas","signature"][[1]]
DCosta.2020.SciReports <- gsign_kidney["DCosta.2020.SciReports","signature"][[1]]
```


# Chord data

```{r}

# use this function to make row or column names bold
# parameters:
#   mat: the matrix passed to pheatmap
#   rc_fun: either rownames or colnames
#   rc_names: vector of names that should appear in boldface
make_bold_names <- function(mat, rc_fun, rc_names) {
  bold_names <- rc_fun(mat)
  ids <- rc_names %>% match(rc_fun(mat))
  ids %>%
    walk(
      function(i)
        bold_names[i] <<-
        bquote(bold(.(rc_fun(mat)[i]))) %>%
        as.expression()
    )
  bold_names
}

source("../codes/GOChord.R")
```

# Chord mRMR

```{r message=FALSE, warning=FALSE, include=FALSE}

sets_list <- c("Rpart", "XGBoost", "Boruta", "RFE", "GBM", "mRMR") 

#Check the set genes intersected with mRMR
d <- genes_matrix
target_cols <- c("mRMR")
other_cols <- colnames(d)[!(colnames(d) %in% c(sets_list, "gene", "genes_papers", "logFC.M0.M1", "logFC.NT.TP", "nlog10FDR.M0.M1", "nlog10FDR.NT.TP"))]
cols_sets <- d %>% filter_at(vars(all_of(target_cols)), ~.==1) %>% select_at(vars(any_of(other_cols))) %>%  colSums(.) > 0
cols_sets <- names(cols_sets)[cols_sets]

circ_dcols <- c("Category","ID","Term","Genes","adj_pval")

circ_data <- as.data.frame(matrix(nrow = length(cols_sets), ncol = length(circ_dcols)))

for(i in c(1:length(cols_sets)) ){
  circ_data[i,] <- list("X", cols_sets[i],cols_sets[i], paste0( get(cols_sets[i]), collapse=", "), 0 )
}

names(circ_data) <- circ_dcols
mRMR <- setdiff(mRMR, c("age"))

#circ_genelist <- as.data.frame(matrix(nrow = length(mRMR), ncol = 2))

circ_genelist <- genes_matrix[mRMR, c("gene", "nlog10FDR.M0.M1")]
rownames(circ_genelist) <- circ_genelist$gene
colnames(circ_genelist) <- c("ID", "logFC")

# Generate the plotting object
circ <- circle_dat(circ_data, circ_genelist)

# Create the plot
chord <- chord_dat(data = circ, genes = circ_genelist, process = circ_data$ID)

chord  <- cbind(chord, genes_matrix[rownames(chord),"logFC.NT.TP"])

p_chord <- GOChordnew(chord,
        gene.order = 'logFC',
        nlfc = 2,
        gene.size = 4.5, 
        gene.space = 0.22,
        space = 0.01,  
        border.size= 0.000001, 
        process.label = 12,
        ribbon.col = c('#FF1F5B','#009ADE', '#00CD6C', '#AF58BA' , '#FFC61E', '#F28522', '#A0B1BA'),  #, '#A6761D', DC3977
        #lfc.col=c('#CF597E','darkgrey','#009392')
        lfc.col=c("#CF597E", "ivory", "#009392")
        )

 pdf(file="figA2_Chord_mRMR.pdf", width = 11, height = 12)
    cowplot::plot_grid(
      p_chord,
      nrow = 1,
      rel_widths = c(0.1, 1, 0.1)
      )
  dev.off()

# grid.newpage()
# p_chord
# row_bot = grid.grab()
# 
# row_top <- cowplot::plot_grid(NULL, grobTree(pvenn), NULL, p1, NULL,  p2, NULL,
#                      #label_size = 20,
#                      labels = c("a", "", "b", "", "c"), 
#                      nrow=1, rel_widths = c(0.05, 1, 0.2, 1, 0.2, 1, 0.05))
# 
# pdf(file="fig2_chord_mRMR.pdf", width = 14, height = 14)
#   cowplot::plot_grid(
#     row_top,  row_bot,
#     ncol = 1,
#     labels = c("", "d"),
#     rel_heights = c(0.3, 1)
#     )
# dev.off()
```

