---
title: "R Notebook Preprocessing and Download of Count Data"
output: html_notebook
---

# Installing and Loading Libraries            

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
packages_bioconductor = c("TCGAbiolinks", "SummarizedExperiment", "DESeq2", "Glimma", "limma","biomaRt", "genefilter")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed from Bioconductor and loaded
package.check <- lapply(packages_bioconductor, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    BiocManager::install(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
}) 

packages_cran = c("DT", "tidyverse","dplyr", "tibble", "stringr", "data.table", "genefilter", "ggrepel")
  
#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed from CRAN and loaded
package.check <- lapply(packages_cran, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

rm(packages_cran, packages_bioconductor, package.check)
```


# Downloading TCGA-KIRC clinical data from Xenabrowser


```{r}
# Survival data
# https://xenabrowser.net/datapages/?dataset=TCGA-kirc.surviival.tsv&host=https%3A%2F%2Fgdc.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443
        
url <- "https://gdc-hub.s3.us-east-1.amazonaws.com/latest/TCGA-KIRC.survival.tsv.gz"
destfile <- "../data/kirc_survival.tsv.gz"
download.file(url, destfile)
kirc.survi <- read_tsv(gzfile("../data/kirc_survival.tsv.gz"))

kirc.survi <- kirc.survi %>% 
  mutate(sample = str_replace_all(sample, "-", ".")) %>% 
  column_to_rownames("sample") %>% 
  rename(status = OS, obs.time = OS.time, patient_id = '_PATIENT')
  
kirc.survi <- as.data.frame(kirc.survi)

# Transform days to months? / 30.43945


# Clinical data
# https://xenabrowser.net/datapages/?dataset=TCGA-KIRC.GDC_phenotype.tsv&host=https%3A%2F%2Fgdc.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443
url <- "https://gdc-hub.s3.us-east-1.amazonaws.com/latest/TCGA-KIRC.GDC_phenotype.tsv.gz"
destfile <- "../data/kirc_clinical.tsv.gz"
download.file(url, destfile)
kirc.clini <- read_tsv(gzfile("../data/kirc_clinical.tsv.gz"))

kirc.clini <- kirc.clini %>%
  dplyr::select(c("submitter_id.samples","prior_malignancy.diagnoses","age_at_initial_pathologic_diagnosis", "gender.demographic",
           "sample_type_id.samples", "pathologic_M", "pathologic_N", "pathologic_T")) %>% 
  rename(sample = 'submitter_id.samples', 
         prior.dx = 'prior_malignancy.diagnoses', 
         age = 'age_at_initial_pathologic_diagnosis', 
         gender = 'gender.demographic',
         sample.type = 'sample_type_id.samples',
         metastasis = 'pathologic_M',
         neoplasm = 'pathologic_N',
         ajcc.stage = 'pathologic_T') %>% 
  mutate(sample.type = str_replace_all(sample.type, "01", "TP") ) %>% 
  mutate(sample.type = str_replace_all(sample.type, "11", "NT") ) %>% 
  filter(sample.type %in% c("TP", "NT")) %>%  
  mutate(sample = str_replace_all(sample, "-", ".")) %>% 
  filter(sample %in% row.names(kirc.survi)) %>% 
  column_to_rownames("sample") %>% 
  mutate_if(is.character,as.factor)
  
kirc.clini <- cbind(kirc.clini, kirc.survi[rownames(kirc.clini),])

kirc.clini$codes <- rownames(kirc.clini)

rm(kirc.survi)

```


# Downloading TCGA-KIRC counts from Xenabrowser

```{r}
# https://xenabrowser.net/datapages/?dataset=TCGA-KIRC.htseq_counts.tsv&host=https%3A%2F%2Fgdc.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443

url <- "https://gdc-hub.s3.us-east-1.amazonaws.com/latest/TCGA-KIRC.htseq_counts.tsv.gz"
destfile <- "../data/kirc_counts.tsv.gz"
download.file(url, destfile)
kirc.count <- read_tsv(gzfile("../data/kirc_counts.tsv.gz"))
kirc.count <- as.data.frame(kirc.count)
colnames(kirc.count) <- gsub("-", "\\.", colnames(kirc.count))
row.names(kirc.count) <- sub("\\..*", "", kirc.count$Ensembl_ID)
kirc.count$Ensembl_ID <- NULL

kirc.count <- 2^(kirc.count)-1
kirc.count <- round(kirc.count, digits = 0)

rm(url, destfile)

```

# Select anotation dataset

```{r}
# If you haven't already installed devtools...
#install.packages("devtools")

# Use devtools to install the package
#devtools::install_github("stephenturner/annotables")

library(annotables)

kirc.annot <- grch38 %>%
  dplyr::filter(grch38$ensgene %in%  row.names(kirc.count)) %>%
  dplyr::select(ensgene, symbol, description)

```


# Filtering Counts and Clinical data

```{r}
kirc.annot <- kirc.annot[!duplicated(kirc.annot$symbol), ]

kirc.annot.miRNA <-  kirc.annot %>% 
  dplyr::filter(grepl("^microRNA", description))

kirc.annot.miRNA <-  kirc.annot %>% 
  dplyr::filter(grepl("^MIR", symbol))

kirc.count.miRNA <- kirc.count[kirc.annot.miRNA$ensgene,]
rownames(kirc.count.miRNA) <- kirc.annot.miRNA$symbol

kirc.count <- kirc.count[kirc.annot$ensgene,]
rownames(kirc.count) <- kirc.annot$symbol

kirc.clini <- kirc.clini[rownames(kirc.clini) %in% colnames(kirc.count), ]
kirc.clini <- kirc.clini[!is.na(kirc.clini$sample.type),]
kirc.count <- kirc.count[,colnames(kirc.count) %in% rownames(kirc.clini)]

```


```{r}
save(kirc.count, kirc.clini, kirc.annot, file="../data/kirc_count.RData", compress=T)
```

# Conditions files of Sample Type for R-Peridot

```{r}

codes.type <- kirc.clini %>% 
                filter(sample.type %in% c("TP", "NT")) %>%   
                rownames_to_column("samples") %>%
                dplyr::select(samples)  %>%
                as_vector(.)

write.table(kirc.count[,codes.type], "../data/misc/peridot/kirc_type.tsv", quote = F, sep = "\t")

## Conditions file
cond <- kirc.clini %>% 
  filter(sample.type %in% c("TP", "NT")) %>%   
  rownames_to_column("samples") %>%
  dplyr::select("samples", "sample.type")

row.names(cond) <- NULL
cond$sample.type <- as.factor(ifelse(cond$sample.type == "NT", "condition0","condition1"))
colnames(cond) <- c("samples", "condition")

write.table(cond, "../data/misc/peridot/kirc_type.tsv.conditions", quote = F, sep = "\t", row.names = F)

rm(codes.type, cond)

```


# Conditions files of Metastasis for R-Peridot


```{r}

# Selecting only samples with M0 or M1 of Primary Tumors cases:
codes.metas <- kirc.clini %>% 
                filter(sample.type == "TP") %>%  
                filter(metastasis %in% c("M0", "M1")) %>%    
                rownames_to_column("samples") %>%
                dplyr::select(samples)  %>%
                as_vector(.)

write.table(kirc.count[,codes.metas], "../data/misc/peridot/kirc_metas.tsv", quote = F, sep = "\t")

## Conditions file
cond <- kirc.clini %>% 
  filter(sample.type == "TP") %>%  
  filter(metastasis %in% c("M0", "M1")) %>% 
  rownames_to_column("samples") %>%
  dplyr::select("samples", "metastasis")

row.names(cond) <- NULL
cond$metastasis <- as.factor(ifelse(cond$metastasis == "M0", "condition0","condition1"))
colnames(cond) <- c("samples", "condition")

write.table(cond, "../data/misc/peridot/kirc_metas.tsv.conditions", quote = F, sep = "\t", row.names = F)

rm(codes.metas, cond)
```









